export const page = {
  home: "/",
  explore: "/explore",
  reels: "/reels",
  inbox: "/inbox",
  signup: "/auth/signup",
  emailVerification: "/auth/email-verification",
  login: "/auth",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  settings: "/settings",
  changeUsername: "/settings/change-username",
  changePassword: "/settings/change-password",
  postDetail: (id: string) => `/post/${id}`,
  profile: (username: string) => `/${username}`,
};
